# Generated by Django 6.0.1 on 2026-01-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('installment_1', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('installment_2', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('installment_3', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('installment_4', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_record', to='accounts.studentprofile')),
            ],
        ),
    ]
