# Generated by Django 6.0.3 on 2026-05-12 09:08

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerecord',
            name='installment_1',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', validators=[accounts.validators.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='installment_2',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', validators=[accounts.validators.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='installment_3',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', validators=[accounts.validators.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='installment_4',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', validators=[accounts.validators.validate_pdf_file]),
        ),
    ]
