# Generated by Django 6.0.3 on 2026-05-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activesession_and_more'),
        ('fees', '0002_alter_feerecord_installment_1_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feerecord',
            index=models.Index(fields=['student'], name='fee_student_idx'),
        ),
    ]
