# Generated by Django 6.0.1 on 2026-02-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='temp_user', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
